# Generated by Django 3.2.6 on 2021-08-12 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=100)),
                ('google_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('picture', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminParentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminTutorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('year_level', models.CharField(max_length=80)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('id_str', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('first_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='', max_length=80)),
                ('email', models.CharField(default='', max_length=100)),
                ('credits', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('picture', models.TextField(blank=True, default='', null=True)),
                ('files', models.CharField(default='', max_length=100)),
                ('first_buy', models.BooleanField(default=False)),
                ('first_use', models.BooleanField(default=False)),
                ('first_time_user', models.BooleanField(default=True)),
                ('fake_user', models.BooleanField(default=False)),
                ('referrer_code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('referrer_method', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('other_referrer', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('survey', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declined_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.IntegerField(default=0)),
                ('extra_files', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=50)),
                ('is_favourite', models.BooleanField(default=False)),
                ('topics', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('special_request', models.CharField(blank=True, max_length=200, null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_join_link', models.CharField(default='', max_length=1000)),
                ('tutee_join_link', models.CharField(default='', max_length=1000)),
                ('active', models.CharField(max_length=50)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requests')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('credits', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('timesBought', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived', models.BooleanField(default=False)),
                ('commission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_field', models.CharField(max_length=80)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('id_str', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('first_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='', max_length=80)),
                ('email', models.CharField(default='', max_length=100)),
                ('school', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('course', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('achievements', models.TextField(blank=True, default='', null=True)),
                ('rating', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('picture', models.TextField(blank=True, default='', null=True)),
                ('files', models.CharField(default='', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_type', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('first_time_user', models.BooleanField(default=True)),
                ('fake_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='', max_length=80)),
                ('sex', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=100)),
                ('subjects', models.CharField(default='', max_length=200)),
                ('achievements', models.CharField(blank=True, default='', max_length=500)),
                ('tutoring_experience', models.CharField(default='', max_length=1000)),
                ('grade_levels', models.CharField(default='', max_length=1000)),
                ('identification_photo', models.CharField(default='', max_length=1000)),
                ('TOR', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('resume', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('facebook_link', models.CharField(default='', max_length=1000)),
                ('school', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('year_of_graduation', models.IntegerField()),
                ('other_info', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_account_number', models.CharField(max_length=200)),
                ('bank_account_name', models.CharField(max_length=200)),
                ('bank_account_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UniquePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoCode', models.CharField(max_length=1000, unique=True)),
                ('promoName', models.CharField(max_length=1000)),
                ('discount', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('terminationPeriod', models.DateTimeField(default=django.utils.timezone.now)),
                ('linkedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopitem')),
            ],
        ),
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=100)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(default='', max_length=1000)),
                ('week_bracket', models.CharField(max_length=200)),
                ('isPaid', models.BooleanField(default=False)),
                ('session', models.ManyToManyField(related_name='sessions', to='core.Session')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('notification', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='SourcePayMongoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_id', models.TextField()),
                ('pay_id', models.TextField()),
                ('credits', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tutor'),
        ),
        migrations.AddField(
            model_name='requests',
            name='declined_tutors',
            field=models.ManyToManyField(related_name='declined_tutors', to='core.Tutor'),
        ),
        migrations.AddField(
            model_name='requests',
            name='fav_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='core.tutor'),
        ),
        migrations.AddField(
            model_name='requests',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent'),
        ),
        migrations.AddField(
            model_name='requests',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.CreateModel(
            name='PayMongoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.TextField()),
                ('credits', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
            ],
        ),
        migrations.CreateModel(
            name='ParentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
            ],
        ),
        migrations.CreateModel(
            name='ParentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('notification', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_seen', models.BooleanField(default=False)),
                ('tutor_seen', models.BooleanField(default=False)),
                ('sender', models.CharField(max_length=200)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoCode', models.CharField(max_length=1000, unique=True)),
                ('promoName', models.CharField(max_length=1000)),
                ('discount', models.FloatField()),
                ('maxUsage', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('promoPeriod', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopitem')),
                ('usedBy', models.ManyToManyField(blank=True, related_name='used_by', to='core.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=200)),
                ('receiver_email', models.CharField(max_length=200)),
                ('is_report', models.BooleanField()),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('add_credit', models.IntegerField()),
                ('subtract_credit', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent'),
        ),
        migrations.CreateModel(
            name='BrankasTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.TextField()),
                ('ref_id', models.TextField()),
                ('credits', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requests')),
            ],
        ),
        migrations.CreateModel(
            name='AdminTutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_seen', models.BooleanField(default=False)),
                ('tutor_seen', models.BooleanField(default=False)),
                ('sender', models.CharField(max_length=200)),
                ('at_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.admintutorconversation')),
            ],
        ),
        migrations.AddField(
            model_name='admintutorconversation',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor'),
        ),
        migrations.CreateModel(
            name='AdminParentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_seen', models.BooleanField(default=False)),
                ('parent_seen', models.BooleanField(default=False)),
                ('sender', models.CharField(max_length=200)),
                ('ap_conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adminparentconversation')),
            ],
        ),
        migrations.AddField(
            model_name='adminparentconversation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent'),
        ),
    ]
