# Generated by Django 3.2.6 on 2021-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='zoominfo',
        ),
        migrations.AddField(
            model_name='subject',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
