# Generated by Django 3.2.6 on 2021-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='declined_tutors',
            field=models.ManyToManyField(blank=True, null=True, related_name='declined_tutors', to='core.Tutor'),
        ),
    ]
