# Generated by Django 3.2.6 on 2021-08-11 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210811_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='id_str',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='parent',
            name='id_str',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='id_str',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
