# Generated by Django 3.2.6 on 2021-08-12 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210811_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
