# Generated by Django 3.2.6 on 2021-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210930_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
