# Generated by Django 3.2.6 on 2021-09-30 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_linktracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktracker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
